# Generated by Django 5.0b1 on 2023-11-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        ("retail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="partner_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to="retail.partner",
                verbose_name="Partner profile",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shops",
            field=models.ManyToManyField(
                blank=True, null=True, to="retail.shop", verbose_name="Shops"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
