# Generated by Django 5.0b1 on 2023-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("retail", "0002_rename_created_report_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="shops",
            field=models.ManyToManyField(
                blank=True, to="retail.shop", verbose_name="Shops"
            ),
        ),
    ]
