# Generated by Django 5.0b1 on 2023-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="report",
            name="period",
        ),
        migrations.AddField(
            model_name="report",
            name="started_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Shift start"),
        ),
        migrations.AddField(
            model_name="report",
            name="stopped_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Shift stop"),
        ),
    ]
