# Generated by Django 5.0b1 on 2023-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail", "0002_rename_created_report_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="started_at",
            field=models.DateTimeField(verbose_name="Shift start"),
        ),
        migrations.AlterField(
            model_name="report",
            name="stopped_at",
            field=models.DateTimeField(verbose_name="Shift stop"),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="receipt",
            field=models.FileField(
                blank=True, upload_to="retail-report-receipts/%Y/%m/%d/"
            ),
        ),
    ]
